# Generated by Django 5.1.4 on 2025-03-01 16:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="hashed_master_password",
            field=models.CharField(
                default=api.models.default_hashed_password, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
